project:
  type: website
  output-dir: gh-pages
  preview:
    port: 5567
website:
  title: "phlo.info"
  site-url: https://phlo.info
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/YoungPhlo
      - icon: twitter
        href: https://twitter.com/YoungPhlo_
format:
  html:
    theme: sandstone
    css: styles.css