project:
  type: website
  output-dir: gh-pages
  preview:
    port: 5567
website:
  title: "phlo.info"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/YoungPhlo
      - icon: twitter
        href: https://twitter.com/YoungPhlo_
  site-url: https://phlo.info
  google-analytics: G-177976EM3E
  twitter-card: true
  open-graph: true

format:
  html:
    theme: sandstone
    css: styles.css