project:
  type: website
  output-dir: gh-pages

website:
  title: "phlo.info"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/YoungPhlo
      - icon: twitter
        href: https://twitter.com/YoungPhlo_
format:
  html:
    theme: lux
    css: styles.css



